server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activityhub?serverTimezone=GMT
    username: root
    password: 521356
    ## 连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 超时时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000

    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;
# mybatis config
mybatis:
  typeAliasesPackage: cn.kepu.questionnaire.pojo
  mapperLocations: classpath*:/mapping/*.xml
mapper:
  mappers: MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
live:
  rtmp-url: rtmp://localhost/live/test
  backup-path: E:\\static\\backupVideo\\
  backup-path-virtual: EpicWorkVideos/mVids/
  pic-path: E:\\static\\video-pic\\
  pic-path-virtual: /ActivityPic/
wechat:
  qrpath: E:\\static\\